version: '3'
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: always
    ports: 
    - "9117:9117"
    volumes:
    - "/etc/localtime:/etc/localtime:ro"
  sonarr:
    image: linuxserver/sonarr:develop
    links:
    - transmission:transmission
    container_name: sonarr
    restart: always
    environment: 
    - PGID=20
    - PUID=501
    ports: 
    - "8989:8989"
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./sonarr_config:/config
    - ./sonarr_tv:/tv
    - ./sonarr_downloads:/downloads
  radarr:
    image: linuxserver/radarr
    links: 
    - transmission:transmission
    container_name: radarr
    restart: always
    environment:
    - PGID=20
    - PUID=501
    ports: 
    - 7878:7878
    volumes: 
    - /etc/localtime:/etc/localtime:ro
    - ./radarr_config:/config
    - ./radarr_movies:/movies
    - ./radarr_downloads:/downloads
  transmission:
    image: dperson/transmission
    container_name: transmission
    ports:
    - 9091:9091
    volumes:
    # In order to the container uses the same date which is in the host, it is necessary to share /etc/localtime file
    - /etc/localtime:/etc/localtime:ro
    - ./tvshows:/var/lib/transmission-daemon/downloads:rw
